/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package endecription;

import java.awt.Color;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Chathura
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    EnCrpt fn = new EnCrpt();
    DeCrpt dc = new DeCrpt();
    public Main() {
        initComponents();
        txtKey.setToolTipText("please enter 9 characters,Don't use only numerics");
        this.clear();
        this.setLocationRelativeTo(null);
        btnOpen.setToolTipText("Select Your Text File..");
  
    }
    public void clear(){
        btnEncode.setEnabled(false);
        btnDecode.setEnabled(false);
        txtKey.setText("Enter Your KeyCode Here");
        txtMsg.setText(null);
        encodedTxtMsg.setText(null);
        bkTotxt.setText(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRst = new javax.swing.JButton();
        btnOpen = new javax.swing.JButton();
        txtKey = new javax.swing.JTextField();
        btnEncode = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        bkTotxt = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMsg = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        encodedTxtMsg = new javax.swing.JTextArea();
        btnDecode = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1182, 534));
        setMinimumSize(new java.awt.Dimension(1182, 534));
        setPreferredSize(new java.awt.Dimension(1182, 534));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRst.setText("Reset");
        btnRst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRstActionPerformed(evt);
            }
        });
        getContentPane().add(btnRst, new org.netbeans.lib.awtextra.AbsoluteConstraints(993, 370, 140, -1));

        btnOpen.setText("Open File");
        btnOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenActionPerformed(evt);
            }
        });
        getContentPane().add(btnOpen, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        txtKey.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtKeyMouseClicked(evt);
            }
        });
        txtKey.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtKeyKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtKeyKeyTyped(evt);
            }
        });
        getContentPane().add(txtKey, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, 210, -1));

        btnEncode.setText("Encode =>");
        btnEncode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEncodeActionPerformed(evt);
            }
        });
        getContentPane().add(btnEncode, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 200, 97, -1));

        bkTotxt.setColumns(20);
        bkTotxt.setRows(5);
        jScrollPane3.setViewportView(bkTotxt);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 480, 160));

        txtMsg.setColumns(20);
        txtMsg.setRows(5);
        jScrollPane1.setViewportView(txtMsg);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 480, 165));

        encodedTxtMsg.setColumns(20);
        encodedTxtMsg.setRows(5);
        jScrollPane2.setViewportView(encodedTxtMsg);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 180, 472, 165));

        btnDecode.setText("<= Decode");
        btnDecode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDecodeActionPerformed(evt);
            }
        });
        getContentPane().add(btnDecode, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 310, 100, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/endecription/white-wallpapers-8.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setAcceptAllFileFilterUsed(false);
        FileNameExtensionFilter filter = new FileNameExtensionFilter(".txt","txt");
        chooser.setFileFilter(filter);
        chooser.setApproveButtonText(null);
        int result = chooser.showSaveDialog(this);
//        if (result == JFileChooser.APPROVE_OPTION){
//            System.out.println("blah blah blah");
//            
//        }
        if(result == JFileChooser.CANCEL_OPTION){
//            JOptionPane.showMessageDialog(Main.this, "Cancelled","FCDemo",JOptionPane.OK_OPTION);
//            System.out.println("Canceled");

        }
        else{
            
            File f = chooser.getSelectedFile();
            String filename = f.getAbsolutePath();
            try {
                fn.readTxt(filename, txtMsg);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnOpenActionPerformed

    private void btnEncodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEncodeActionPerformed
        encodedTxtMsg.setText(fn.readLines(txtMsg,fn.cnvrtKey(txtKey.getText())));
        
        btnDecode.setEnabled(true);
    }//GEN-LAST:event_btnEncodeActionPerformed

    private void txtKeyKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKeyKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKeyKeyPressed

    private void txtKeyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKeyKeyTyped
        int c = evt.getKeyCode();
        if (txtKey.getText().length() > 8) {
            evt.consume();
            btnEncode.setEnabled(true);
        }else{

            btnEncode.setEnabled(false);
        }
    }//GEN-LAST:event_txtKeyKeyTyped

    private void btnDecodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDecodeActionPerformed
        bkTotxt.setText(dc.readLines(encodedTxtMsg, fn.cnvrtKey(txtKey.getText())));
        btnEncode.setEnabled(false);
    }//GEN-LAST:event_btnDecodeActionPerformed

    private void btnRstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRstActionPerformed
        this.clear();
    }//GEN-LAST:event_btnRstActionPerformed

    private void txtKeyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtKeyMouseClicked
        txtKey.setText(null);
    }//GEN-LAST:event_txtKeyMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea bkTotxt;
    private javax.swing.JButton btnDecode;
    private javax.swing.JButton btnEncode;
    private javax.swing.JButton btnOpen;
    private javax.swing.JButton btnRst;
    private javax.swing.JTextArea encodedTxtMsg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField txtKey;
    private javax.swing.JTextArea txtMsg;
    // End of variables declaration//GEN-END:variables
}
